Feature/like
shinonome-inc/backend-final-assignment-Nozomi pull request #10
Opened 2023-05-24 08:26 UTC by NakaiNozomi

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-05-25 02:19 UTC, harune-pg commented
プロフィール画面とツイート詳細画面でいいね機能が実装されていません

2023-05-25 03:18 UTC, harune-pg requested changes

2023-05-25 03:18 UTC, harune-pg commented on tweets/views.py
>  class HomeView(LoginRequiredMixin, TemplateView):
ホーム画面で各ツイートがいいねされているか見た目でわからなくなっています。各ツイートがいいねされているかの情報をcontext に渡してください。

2023-05-25 03:18 UTC, harune-pg commented on templates/tweets/detail.html
> +        <p>いいね数</p><span id="count_{{tweet.id}}">{{tweet.likes.count}}</span>
いいね数を取得できていません。Likeモデルを見返してみてください。

2023-05-25 23:38 UTC, harune-pg requested changes

2023-05-25 23:38 UTC, harune-pg commented on tweets/views.py
> +        )
N+1問題が発生しています

2023-05-25 23:38 UTC, harune-pg commented on tweets/views.py
> +        )
N+1問題が発生しています

2023-05-25 23:38 UTC, harune-pg commented on accounts/views.py
> +        )
N+1問題が発生しています

2023-05-25 23:38 UTC, harune-pg commented on templates/tweets/home.html
> +{% load static %}
staticファイルを扱っていないのでここの記述は不要です。

2023-05-25 23:38 UTC, harune-pg commented on tweets/views.py
>  class HomeView(LoginRequiredMixin, TemplateView):
「いいねされているか見た目で分かる」は、いいねに応じてハートの色を変えるでも大丈夫です！
もちろん、現在のテキストで表す方法でも大丈夫ですが、上記のコメントがわかりにくかったので、補足しておきます。

2023-05-25 23:50 UTC, NakaiNozomi commented on tweets/views.py
>  class HomeView(LoginRequiredMixin, TemplateView):
ハートでやろうとしたらうまくいかなかったのでテキストで表す方法に変更しました。

2023-05-26 03:15 UTC, harune-pg commented on tweets/views.py
> +        )
コメント行を間違えました、すみません。正しくは、context["tweet_list"]が原因で発生しています。

2023-05-26 03:17 UTC, harune-pg commented on accounts/views.py
> +        )
コメント行を間違えました、すみません。正しくは、context["tweet_list"]が原因で発生しています。

2023-05-26 03:20 UTC, harune-pg commented on tweets/views.py
> +        )
こちらの勘違いでした、修正する必要はありません。

2023-05-26 03:33 UTC, harune-pg commented
コメントに間違いがあったので、追記しました。

また、django-debug-toolbarの設定方法に困っていたら、以下のページを参考にしてみて下さい。
https://shinonome-inc.notion.site/SQL-N-1-django-debug-toolbar-26315565b11d491fb21078f1883710aa

2023-05-27 04:27 UTC, harune-pg requested changes
最後に、細かいところですが確認お願いします！

2023-05-27 04:27 UTC, harune-pg commented on accounts/views.py
>  from .admin import User
Userモデルのimportで、accounts.adminを経由しているのは何か理由がありますか？
もしないようだったたら、accounts.modelsから直接importした方が良いと思います！

2023-05-27 04:27 UTC, harune-pg commented on templates/tweets/detail.html
>          <p>コメント：{{object.content}}</p>
DetailViewでは、デフォルトでcontextに「object」というキーと、modelの値を小文字化したキーが入ります。これらのキーのバリューはどちらも同じで、modelに指定したモデルのインスタンスが入っています。いま、下に続くlike.htmlにおいてtweetの方を用いているので、ここでもobject→tweetとして統一した方がわかりやすいです！

2023-05-27 04:28 UTC, harune-pg commented on templates/tweets/home.html
> +{% load static %}
base.htmlでも同様です。

2023-05-27 05:08 UTC, NakaiNozomi commented on accounts/views.py
>  from .admin import User
特に理由はないく、どっちからimportしてもあまり変わらないかなと思いadminからimportしました。

2023-05-27 05:25 UTC, harune-pg approved these changes
LGTM

2023-05-29 15:11 UTC, kenketsu approved these changes
良くかけていると思います！！

2023-05-29 15:12 UTC, merged