ログイン機能
shinonome-inc/backend-final-assignment-Nozomi pull request #7
Opened 2023-03-23 22:47 UTC by NakaiNozomi

## 受講生の確認事項

- [x] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [x] Django Adminに，今まで作成したモデルを全て登録した
- [x] テスト要件のテストを全て実装した
- [x] CI が全て通った

## １次レビュアーの確認事項

- [x] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-03-27 12:31 UTC, kunikida007 commented
CIの実行が通っていないので通してください。
それと、adminにmodelの追加をお願いします。

2023-03-27 12:31 UTC, kunikida007 commented
CIの実行が通っていないので通してください。
それと、adminにmodelの追加をお願いします。

2023-03-27 12:31 UTC, kunikida007 commented
CIの実行が通っていないので通してください。
それと、adminにmodelの追加をお願いします。

> ## 受講生の確認事項
> * [x]  画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
> * [x]  Django Adminに，今まで作成したモデルを全て登録した
> * [x]  テスト要件のテストを全て実装した
> * [x]  CI が全て通った
> 
> ## １次レビュアーの確認事項
> * [x]  [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

CIの実行が通っていないので通してください。
それと、adminにmodelの追加をお願いします。

2023-03-27 12:55 UTC, kunikida007 commented
テストの実行結果のスクリーンショットをお願いします。

2023-03-28 03:39 UTC, kunikida007 approved these changes

2023-03-28 14:25 UTC, Akinori13 requested changes
良い感じです！少しコメントしました！

ログインへのリンクとログアウトするフォームをbase.htmlに追加しましょう！

2023-03-28 14:25 UTC, Akinori13 commented on 2.0.0
必要ないファイルは削除しましょう！

2023-03-28 14:25 UTC, Akinori13 commented on accounts/views.py
>          return response
サインアップ時のリダイレクト先をLOGIN_REDIRECT_URLにしましょう！

2023-03-28 14:25 UTC, Akinori13 commented on accounts/views.py
>  # from django.shortcuts import render
使用していないものは消しちゃってください！

2023-03-28 14:25 UTC, Akinori13 commented on accounts/views.py
UserProfileViewを作成しましょう

2023-03-28 14:25 UTC, Akinori13 commented on accounts/views.py
> +from django.contrib.auth.views import LoginView, LogoutView
importしたLoginViewとLogoutViewと名称が被っていない。
```
# Bad
from django.contrib.auth views import LoginView
class LoginView(LoginView):

# OK
from django.contrib.auth import views as auth_views
class LoginView(auth_views.LoginView):
```

2023-03-29 12:59 UTC, Akinori13 requested changes
少しコメントしました！

2023-03-29 12:59 UTC, Akinori13 commented on accounts/views.py
> +    template_name = "accounts/login.html"
これ必要ですか

2023-03-29 12:59 UTC, Akinori13 commented on templates/base.html
> +      <a href={% url "accounts:logout" %}>ログアウト</a>
ログアウトはformタグで送信しましょう。aタグだとgetリクエストになります

2023-03-29 16:37 UTC, Akinori13 commented
LGTM

2023-03-29 16:37 UTC, merged