Feature/tweet
shinonome-inc/backend-final-assignment-Nozomi pull request #8
Opened 2023-04-09 00:59 UTC by NakaiNozomi

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-04-11 15:28 UTC, Rei-Goda requested changes
概形はよくできていてとても良いと思います！細かい点が多いですがいくつかコメントさせていただきました。
また、下記の13点に加えて tweets/admin.pyにてadmin.site.registerにTweetモデルを入れるよう追加してください。

2023-04-11 15:28 UTC, Rei-Goda commented on accounts/views.py
> +        return queryset.filter(username=self.kwargs.get("username"))
get_queryset()メソッドの返り値(return)は初期値で既にquerysetなので、super()を用いてget_queryset()メソッドを呼び出している45行目は不要です。
ListViewの定義がまとめられている下記リンクにてget_queryset(self)を参照するとわかりやすいかと思います。
https://ccbv.co.uk/projects/Django/4.1/django.views.generic.list/ListView/

2023-04-11 15:28 UTC, Rei-Goda commented on templates/accounts/profile.html
> +{% load static %}
多くのhtmlで共通して必要となる{% load static %}は、base.htmlの最初に記載しておくとよいです。

2023-04-11 15:28 UTC, Rei-Goda commented on templates/tweets/create.html
> +{% url 'tweets:create' %}
urls.pyにて対応するhtmlを指定できているため、1行目は削除して大丈夫です。
また、各機能のhtmlでもbase.htmlを継承してください。

2023-04-11 15:28 UTC, Rei-Goda commented on templates/tweets/delete.html
> +{% url 'tweets:delete' pk %}
こちらもcreate.htmlと同様

2023-04-11 15:28 UTC, Rei-Goda commented on templates/tweets/delete.html
> +    <input type="submit" value="削除する">
機能上は問題ありませんが、削除する際はdetail.htmlのようにツイート内容を表示した方がより親切です。

2023-04-11 15:28 UTC, Rei-Goda commented on templates/tweets/detail.html
> +        <p>タイトル：{{object.title}}</p>
ツイート機能に投稿のタイトル機能は不要ですし、Tweetモデルにも対応するフィールドが無いので削除して大丈夫です。

2023-04-11 15:28 UTC, Rei-Goda commented on templates/tweets/home.html
> +    </div>
13行目にて、これでは現在時刻が表示されてしまうと思うので、item.created_at等の形で投稿された日時を表示するようにしてください。
また、ツイートの内容についても表示してください。

2023-04-11 15:28 UTC, Rei-Goda commented on accounts/views.py
>      slug_url_kwarg = "username"
urlのナンバリングをpkにて行っているようなので、slugの設定は削除して大丈夫です。

2023-04-11 15:28 UTC, Rei-Goda commented on accounts/views.py
> +        context["tweet_list"] = Tweet.objects.all()
これではtweet_listをfor文で読み込む際にN+1問題が起こってしまうので、select_relatedを用いてください。
Tweet.objects.all()　->   Tweet.objects.select_related("user").filter(user=user)
のようにすれば良いと思います。

2023-04-11 15:28 UTC, Rei-Goda commented on tweets/views.py
> +        return Tweet.objects.filter(user=self.request.user)
Homeでは全ユーザーのツイートを表示するので、現在のユーザーが投稿したもののみにfilterする必要はないです。

2023-04-11 15:28 UTC, Rei-Goda commented on tweets/views.py
> +        context["tweet_list"] = Tweet.objects.all()
こちらもN+1問題が起きてしまうので、Tweet.objecs.select_related("user") 等の形でselect_relatedを用いてください。
余談ですが、HomeViewの定義の時点で(13行目等に)　queryset = Tweet.objects.select_related("user")　としても実装できます。もし前述の形でエラーが出るようならこちらも試してみてください。

2023-04-11 15:28 UTC, Rei-Goda commented on tweets/views.py
> +    fields = ["content"]
この形でも機能上は大丈夫ですが、せっかくtweets/forms.pyにてTweetFormを定義しているので
form_class = TweetForm 
とした方が良いです。

2023-04-11 15:28 UTC, Rei-Goda commented on accounts/tests.py
> +        self.url = reverse("accounts:login")
本テストでは使用していないため、削除して大丈夫です。

2023-04-14 09:25 UTC, Rei-Goda commented on tweets/views.py
> +        return Tweet.objects.filter(user=self.request.user)
説明不足ですみません。filter(user=self.request.user)の部分で、投稿者が現在ログインしているユーザーである投稿のみに絞り込まれてtweets_listに返る状態になっているようです。
また、現状 Tweet.objects の取得の絞り込みはcontext["tweet_list"] で出来ているので、14,15行目は不要です。

2023-04-14 09:51 UTC, Rei-Goda commented
一次LGTMです！

2023-04-16 10:32 UTC, TAK848 requested changes
コメントしたのでご確認お願いします！また以下ご確認お願いします！

1. base.htmlを編集するなどして，tweets/home/や自身のプロフィールページのリンクも貼ってください。
2. Tweet投稿への導線も，templateのわかりやすい位置にリンク設定してください。urlベタ打ちせず，画面遷移だけで各機能にアクセスできるようにしてください。

2023-04-16 10:32 UTC, TAK848 commented on accounts/views.py
> +        return context
このページ開くとこうなるんですが，意図したものでしょうか？
<img width="960" alt="Screenshot 2023-04-16 at 19 19 42" src="https://user-images.githubusercontent.com/41906969/232295798-d81c5903-3228-4c6e-802d-fb11cd4bf9fa.png">

2023-04-16 10:32 UTC, TAK848 commented on tweets/views.py
> +        return context
1. これだとListViewの機能を使っていないです。get_context_dataで全部の値を与えているのでTemplateViewで十分です
2. Tweetのsort，明示的にしてあげると良いと思います

2023-04-16 10:32 UTC, TAK848 commented on tweets/views.py
> +    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)
LOGIN_REDIRECT_URLと意図が違うものなので，settingsからではなく普通に設定しましょう

2023-04-19 10:17 UTC, TAK848 commented
ブラウザで実際に表示のチェックをしていますでしょうか？
https://github.com/shinonome-inc/backend-final-assignment-Nozomi/pull/8/commits/7f9ebfc9a1755acb8e2e1d1ec9e130a764ea32ab
で追記した内容が反映されていなかったり，以下のようにTweet文章が存在しているはずなのに表示されていなかったりします。

動作が確認できないため，今回作成・編集したページで良いので，正常に動作した際のスクリーンショットをページごとに貼ってください！
<img width="1220" alt="Screenshot 2023-04-19 at 19 15 35" src="https://user-images.githubusercontent.com/41906969/233044477-0407ed3e-e9c6-4529-8391-984596433ce9.png">
<img width="583" alt="Screenshot 2023-04-19 at 19 15 11" src="https://user-images.githubusercontent.com/41906969/233044395-a4b27eed-0f87-4cc4-b385-67a3812da5d4.png">

2023-04-20 13:54 UTC, TAK848 commented on templates/base.html
> +      <a href={% url "accounts:user_profile" %}>プロフィール</a>
これを書いて，どこにどう表示されるかテストしましたか？

2023-04-20 13:54 UTC, TAK848 commented on accounts/views.py
> +        return context
ListViewに変更した意図をお聞きしたいです！

2023-04-20 13:54 UTC, TAK848 commented on tweets/views.py
>  # from django.shortcuts import render
remove

2023-04-20 15:10 UTC, NakaiNozomi commented on accounts/views.py
> +        return context
すみません。修正ミスでした。

2023-04-20 15:32 UTC, NakaiNozomi commented on templates/base.html
> +      <a href={% url "accounts:user_profile" %}>プロフィール</a>
今回のpushで、書き方を変更して、どのように表示されるのかも確かめました。

2023-04-21 13:15 UTC, TAK848 commented on accounts/views.py
> +        return context
とりあえず書き換えるだけで無く，変数やメソッドが本当に使われている要素だけか確認してみましょう
例えばmodelは使われていますか？
https://ccbv.co.uk/projects/Django/4.2/django.views.generic.base/TemplateView/

2023-04-21 13:16 UTC, TAK848 commented on templates/base.html
> +      <a href={% url "accounts:user_profile" %}>プロフィール</a>
https://github.com/shinonome-inc/backend-final-assignment-Nozomi/pull/8/commits/7f63beea9f68ba9aea36ace813c5baf290e6a907
こちらで確認できました。OKです！

2023-04-21 13:31 UTC, NakaiNozomi commented on accounts/views.py
> +        return context
確かに使ってないですね。次の機能実装からはもっと気を付けて確認します！

2023-04-21 13:34 UTC, tak848 commented on accounts/views.py
> +        return context
まだつかわれてないものあります…！もう一度確認してください！

2023-04-22 00:53 UTC, TAK848 commented on accounts/views.py
> +        return context
[templates/base.html](https://github.com/shinonome-inc/backend-final-assignment-Nozomi/pull/8/files/019fba3293364290f502d13c5d4381b7c6452fe4#diff-690b81fad8df2a1f1ce37c846641d9247e3472d244f17039d2910a5ed0c98d5e)もそうだけど，自分が書いたコードがどう動いてどういう役割してるか，確認できる箇所はちゃんと確認してくださいね！

2023-04-22 00:53 UTC, TAK848 approved these changes

2023-04-22 00:53 UTC, merged