Feature/follow
shinonome-inc/backend-final-assignment-Nozomi pull request #9
Opened 2023-04-25 02:50 UTC by NakaiNozomi

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-04-25 18:38 UTC, Yamakou621 reviewed
・サインアップのエンドポイントがないので追加してください。
一度実際にrunserverをして動くかを確認してみましょう！

2023-04-25 18:38 UTC, Yamakou621 commented on accounts/models.py
> +    following = models.ForeignKey(User, related_name="follower", on_delete=models.CASCADE)
命名が分かりにくいので変更してください。

2023-04-25 18:38 UTC, Yamakou621 commented on accounts/models.py
> +    follower = models.ForeignKey(User, related_name="following", on_delete=models.CASCADE)
同様です。

2023-04-25 18:38 UTC, Yamakou621 commented on accounts/views.py
> +        context["co_following"] = FriendShip.objects.filter(following=user, follower=self.request.user).exists()
インデントを合わせてください

2023-04-25 18:38 UTC, Yamakou621 commented on accounts/views.py
> +        if follower == following:
if follower == following がTrueの時点で下のif文はやる必要がないので、elseで条件分けしてください。

2023-04-26 03:36 UTC, NakaiNozomi commented on accounts/views.py
> +        context["co_following"] = FriendShip.objects.filter(following=user, follower=self.request.user).exists()
どこがずれているのかが分かりません。

2023-04-26 09:46 UTC, Yamakou621 commented on accounts/models.py
> +    following = models.ForeignKey(User, related_name="follower", on_delete=models.CASCADE)
分かりにくくてすみません。followingとfollowerの、related_nameが分かりにくいので修正してください。

2023-04-26 09:46 UTC, Yamakou621 commented on accounts/views.py
> +        context["co_following"] = FriendShip.objects.filter(following=user, follower=self.request.user).exists()
すみません。こちらのミスでした。

2023-04-26 09:47 UTC, Yamakou621 commented
サインアップのエンドポイントがないので追加してください。

2023-04-26 10:01 UTC, NakaiNozomi commented
> サインアップのエンドポイントがないので追加してください。

サインアップのページは自分では見れるのですが、そちらからは見えませんか？

2023-04-26 10:06 UTC, Yamakou621 commented
home.htmlの作成者のurlが現在ログインしているユーザーになってしまっているので、どのユーザーが作成したツイートでも自分のプロフィールに飛んでしまいます。

2023-04-26 10:09 UTC, Yamakou621 commented
proflie画面のところも、フォローする際のリンク先が今現在ログインしているユーザーになっているので、必ず「自分自身はフォローできません」というエラーが出てしまうと思います。

2023-04-26 10:14 UTC, Yamakou621 commented
> > サインアップのエンドポイントがないので追加してください。
> 
> サインアップのページは自分では見れるのですが、そちらからは見えませんか？

base.htmlにサインアップのページに飛ぶリンクがないので見れないと思います。
どこのリンクから見ていますか？見落としだったらすみません(._.)

2023-04-26 11:58 UTC, NakaiNozomi commented
> proflie画面のところも、フォローする際のリンク先が今現在ログインしているユーザーになっているので、必ず「自分自身はフォローできません」というエラーが出てしまうと思います。

profileの方はそのユーザーのprofileに飛ぶようになったのですが、フォロー問題が全く解決の糸口が見えません。どうしたらいいでしょうか？

2023-04-27 13:36 UTC, Yamakou621 commented
フォローをするときにとってきたい情報は**ツイートを作成したユーザーの情報**です。ではどのように情報を取ってくるかというと、UserProfileViewにて受け渡します。
現在はUserProfileViewでユーザーの情報をcontext["username"] = user.usernameでとってきていますね。しかしこれによって取得できる情報は現在ログインしているユーザーの情報です。つまりここをツイートを作成したユーザーの情報をとってくるようにしたらいいわけです。具体的な方法は調べてみて下さい！
分からなかったらDawnで対応するので連絡して下さい！

contextを表示させる方法は以下の資料を確認してください。
https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?p=1be0fe5323054e23a2165f517c276f3c&pm=s

2023-04-29 11:06 UTC, Yamakou621 commented
・詳細ページからも作成者のページに飛べるようにしてください。
・フォロー、アンフォローでNoReverseMatchが出ます。
・フォロワー一覧、フォロー一覧で表示されるのが「ログインしているユーザー」のもので、該当のユーザーではないです。

**必ずpython manage.py runserverを実行してエラーが出ないかを確認してください。**

2023-05-03 00:31 UTC, Yamakou621 commented
N+1問題が発生しているので解消してください。

2023-05-05 11:41 UTC, Yamakou621 reviewed
修正してくれた場所はよくできています！
UserProfileViewでも起こっているので、そこを修正してください！

2023-05-05 11:41 UTC, Yamakou621 commented on accounts/views.py
> +        return context
ここで起こっています。

2023-05-05 11:42 UTC, Yamakou621 commented on accounts/views.py
>          user = get_object_or_404(User, username=self.kwargs["username"])
ここで起こっています。

2023-05-07 11:32 UTC, Yamakou621 commented
LGTMです！よくかけていると思います！

2023-05-07 13:46 UTC, shunsuke44 requested changes
いくつかコメントをしたので確認をお願いします。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/models.py
> +class Friends(models.Model):
モデル名は同じ意味であれば短い方がいいですが、さすがに`Friends`だとパッと見たときに意味が伝わりにくいと思います。
元のコメントにあった通り`FriendShip`とするか、`FollowRelation`などとするのが良いでしょう。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/models.py
> +        return self.user.username
これ`self.user`は未定義なので`str(friendship)`などとするとエラーになりませんか？

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/views.py
> +            return redirect("tweets:home")
この上の`elif`は`if`で置き換えられ、`else`はいらないです。関数やメソッドで`return`した場合、その時点でその関数またはメソッドの実行は終了するので、無駄なネストを避けるためにも`elif`や`else`が不必要な場面ではつけない方が良いでしょう。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/views.py
> +            return redirect("tweets:home")
ここも`else`いらないです。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/tests.py
> +    def test_failure_post_with_not_exist_tweet(self):
テスト名もともと間違っていたのかもしれないですが、`test_failure_post_with_not_exist_tweet`ではなく`test_failure_post_with_not_exist_user`だと思います。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/tests.py
> +    def test_failure_post_with_incorrect_user(self):
`TestUnfollowView`全体を通して[テスト項目要件](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=128988789)とテストが合致していなさそうなので、再度確認と修正をお願いします。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/views.py
> +        context["co_following"] = (
`co_following`の意味が少し分かりにくいです。`is_following`などとした方が分かりやすいと思います。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/views.py
> +        context["follower"] = Friends.objects.select_related("user").filter(following=user).count()
基本的に`count`や`exist`の結果のみを参照するときには`select_related`は必要ないと思います。
どのようなときにN+1問題が起こるのか再度確認していただくようお願いします。
分からない場合には補足したりするのでいつでも聞いてください。

2023-05-07 13:46 UTC, shunsuke44 commented on templates/accounts/follower_list.html
> +        {% for object in follower_list %}
単に`object`とするよりもっと分かりやすい命名にしましょう。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/views.py
>          return context
すべて`get_context_data`で処理するのであれば`ListView`である必要はなさそうです。
何のために`ListView`を使うのかという部分を再度確認お願いします。
`ListView`を使って書くとすれば、`get_queryset()`のオーバーライドや`context_object_name`変数の定義などを使うとうまく書けると思うので調べてみてください。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/views.py
>          return context
`FollowerListView`も同様にお願いします。

2023-05-07 13:46 UTC, shunsuke44 commented on templates/accounts/following_list.html
> +    {% for object in following_list %}
ここもfor文を使って回しているので、単に`object`とするのではなくもっと分かりやすい命名にしましょう。

2023-05-07 13:46 UTC, shunsuke44 commented on accounts/views.py
> +        context["follower"] = Friends.objects.select_related("user").filter(following=user).count()
あとこの場合はフォローとフォロワーの数をそれぞれ渡しているので、それぞれ`following_count`、`follower_count`などもっと分かりやすい名前で渡してあげた方がいいと思います。

2023-05-07 13:46 UTC, shunsuke44 commented on templates/tweets/home.html
> +        <p>作成者：<a href="{% url 'accounts:user_profile' item.user.username %}">{{item.user.username}}</a></p>
コンテキストに`item`が渡されていないように見えるのですが、この`item.user.username`はちゃんと参照できていますか？

2023-05-07 13:46 UTC, shunsuke44 commented on templates/tweets/home.html
>          <a href="{% url 'tweets:detail' item.pk %}">詳細</a>
ここも

2023-05-07 13:46 UTC, shunsuke44 commented on templates/accounts/profile.html
> +    {% if item.user.username != tweet_user.username %}
ここの`item`はどこの値を参照していますか？

2023-05-07 16:31 UTC, NakaiNozomi commented on accounts/views.py
> +            return redirect("tweets:home")
elifをifに置き換え、elseを消去するとtestでエラーが出ます。

2023-05-07 16:32 UTC, NakaiNozomi commented on accounts/views.py
> +            return redirect("tweets:home")
こちらもでした

2023-05-07 16:32 UTC, NakaiNozomi commented on templates/accounts/profile.html
> +    {% if item.user.username != tweet_user.username %}
このitemは何も参照できていませんでした

2023-05-07 16:34 UTC, NakaiNozomi commented on templates/tweets/home.html
> +        <p>作成者：<a href="{% url 'accounts:user_profile' item.user.username %}">{{item.user.username}}</a></p>
これらはrunserverして表示されていることを確認できました。

2023-05-08 13:19 UTC, shunsuke44 requested changes
いくつかコメントしました。
conversationをもとに修正を確認している部分もあるので、基本的にNozomiさんの側でResolve conversationはしないようにお願いします。
あと修正が漏れている部分があったので再度確認お願いします。

2023-05-08 13:19 UTC, shunsuke44 commented on templates/tweets/home.html
> +        <p>作成者：<a href="{% url 'accounts:user_profile' item.user.username %}">{{item.user.username}}</a></p>
すみません、上のfor文で定義していたんですね。折り畳まれていて見えませんでした。
for文で用いる変数はイテレートするオブジェクトに応じて分かりやすいものをつけるようにしましょう。
今回で言えば`item`よりも`tweet`の方がいいと思います。

2023-05-08 13:19 UTC, shunsuke44 commented on accounts/views.py
> +            FriendShip.objects.select_related("user").filter(following=user, follower=self.request.user).exists()
ここも`select_related`はいらないです。

2023-05-08 13:19 UTC, shunsuke44 commented on accounts/views.py
> +            return redirect("tweets:home")
どんなエラーが出ますか？

2023-05-08 13:19 UTC, shunsuke44 commented on accounts/views.py
> +            return redirect("tweets:home")
どんなエラーが出ていますか？
あと、`select_related`は必要ないです。

2023-05-08 13:19 UTC, shunsuke44 commented on accounts/views.py
>          return context
コンテキストで渡す変数名は`following_friendships`などとした方がいいでしょう。

2023-05-08 13:19 UTC, shunsuke44 commented on templates/accounts/follower_list.html
> +        {% for followed_user in follower_list %}
ここで処理しているのは`user`ではなく`friendship`オブジェクトなので`follower_friendship`などもっと分かりやすい名前を付けましょう。

2023-05-08 13:19 UTC, shunsuke44 commented on templates/accounts/following_list.html
> +    {% for followed_user in following_list %}
ここも

2023-05-08 13:19 UTC, shunsuke44 commented on templates/accounts/profile.html
> +    {% if item.user.username != tweet_user.username %}
修正お願いします。

2023-05-08 13:19 UTC, shunsuke44 requested changes
いくつかコメントしました。
conversationをもとに修正を確認している部分もあるので、基本的にNozomiさんの側でResolve conversationはしないようにお願いします。
あと修正が漏れている部分があったので再度確認お願いします。

2023-05-08 13:43 UTC, NakaiNozomi commented on templates/accounts/profile.html
> +    {% if item.user.username != tweet_user.username %}
これはitemを消去することで解決しました。

2023-05-08 13:47 UTC, NakaiNozomi commented on accounts/views.py
> +            return redirect("tweets:home")
ValueError: The view accounts.views.view didn't return an HttpResponse object. It returned None instead.
このエラーです。

2023-05-08 13:47 UTC, NakaiNozomi commented on accounts/views.py
> +            return redirect("tweets:home")
testしてみたらエラー出ていませんでした

2023-05-08 13:49 UTC, NakaiNozomi commented on accounts/models.py
> +        return self.user.username
ここは自分にはよく分かりませんでした。

2023-05-08 14:33 UTC, shunsuke44 requested changes
コメントしました。
まだいくつか修正漏れがあるようです。
きちんとPull Requestの`Files changed`のタブのページを一通り見て確認していただくようお願いします。

2023-05-08 14:33 UTC, shunsuke44 commented on accounts/views.py
> +            return redirect("tweets:home")
たぶんインデントがずれているせいですね。
`else`を削除したらインデントを一つ左にずらさないと上の`if`文の続きだと認識されてしまうので、そのせいだと思います。

2023-05-08 14:33 UTC, shunsuke44 commented on accounts/views.py
> +            FriendShip.objects.select_related("user").filter(following=user, follower=self.request.user).exists()
修正お願いします。

2023-05-08 14:33 UTC, shunsuke44 commented on accounts/models.py
> +        return self.user.username
たとえば`python manage.py shell`などを利用して適当な`FriendShip`オブジェクトを取得してから`str(friendship)`をすると分かりますが、このモデルには`user`というアトリビュートはないのでエラーになるはずです。
一応補足しておくと`__str__(self)`はオブジェクトを`str()`関数を使用して文字列にするときに呼ばれるメソッドになります。

2023-05-08 14:33 UTC, shunsuke44 commented on accounts/views.py
> +            return redirect("tweets:home")
もともと`else`ブロックに入っていた部分については一つインデントを左にずらさないと`if`の続きとして認識されてしまい評価されません。
エラーが出ていないのはテストでDB側のデータがちゃんと削除されたかどうかのチェックがちゃんとできていないからですね。

2023-05-08 14:33 UTC, shunsuke44 commented on accounts/tests.py
> +        self.assertTrue(FriendShip.objects.filter(follower=self.user1, following=self.user2).exists())
ここは正常に削除された後なので`assertFalse`ですね。

2023-05-08 14:33 UTC, shunsuke44 commented on templates/accounts/profile.html
> +    {% if item.user.username != tweet_user.username %}
上のif文のところ修正できていないですね。

2023-05-08 14:33 UTC, shunsuke44 commented on accounts/models.py
> +    following = models.ForeignKey(User, related_name="follower", on_delete=models.CASCADE)
`related_name`はfollowerだと分かりにくいので`follower_friendships`としたほうがいいと思います。

2023-05-08 14:33 UTC, shunsuke44 commented on accounts/models.py
> +    follower = models.ForeignKey(User, related_name="following", on_delete=models.CASCADE)
同様です。

2023-05-08 14:33 UTC, shunsuke44 requested changes
コメントしました。
まだいくつか修正漏れがあるようです。
きちんとPull Requestの`Files changed`のタブのページを一通り見て確認していただくようお願いします。

2023-05-09 10:37 UTC, shunsuke44 requested changes
いくつかコメントしました。確認お願いします。

2023-05-09 10:37 UTC, shunsuke44 commented on accounts/tests.py
> +from .admin import FriendShip
これ`.admin`からモデルを取ってきてしまっているのはあまり良くないです。
きちんと`.models`からimportするようにしましょう。

2023-05-09 10:37 UTC, shunsuke44 commented on templates/accounts/following_list.html
> +{% if following_friendships %}
ここも

2023-05-09 10:37 UTC, shunsuke44 commented on templates/accounts/follower_list.html
> +{% if follower_friendships %}
ここは`if`文で分岐しても動作はしますが、`{% for %} {% empty %} {% endfor %}`を利用するともっと綺麗にまとまると思います。

2023-05-09 10:37 UTC, shunsuke44 commented on accounts/views.py
> +        friends.delete()
そのまま続けて`.delete()`としてしまった方がわかりやすいと思います。

2023-05-09 10:37 UTC, shunsuke44 commented on accounts/views.py
> +        return context
このままでも動作しますが、せっかくなので`ListVeiw`を使って書き直してみましょう。

2023-05-09 10:37 UTC, shunsuke44 commented on accounts/views.py
>          return context
こちらも同様に書き直してみましょう。

2023-05-09 10:37 UTC, shunsuke44 commented on accounts/views.py
> +from .admin import FriendShip, User
adminではなく`.models`からインポートするようにしましょう。

2023-05-10 12:26 UTC, shunsuke44 requested changes
コメントしました。確認お願いします。

2023-05-10 12:26 UTC, shunsuke44 commented on accounts/models.py
> +        return self.username
これはどんな出力を想定していますか？
`__str__`がどんなことをするメソッドかちゃんと理解しているでしょうか？

2023-05-10 12:48 UTC, NakaiNozomi commented on accounts/models.py
> +        return self.username
改めて調べました。Modelのデータを判別するためのメソッドと理解しました。

2023-05-10 14:00 UTC, shunsuke44 requested changes

2023-05-10 14:00 UTC, shunsuke44 commented on accounts/models.py
> +        return self.username
うーん、というよりPython自体の機能でこのクラスのインスタンスaに対して`str(a)`を実行したときに呼び出されるメソッドです。
それを考えるとそもそもこのクラスに`username`なんて属性はないのでエラーが起きると思います。
このクラスを文字列化したときにこのクラスの属性を使ってどんな表示をしたいかで実装が変わるのでまずはそこを考えて実装してみてください。

2023-05-11 10:13 UTC, shunsuke44 approved these changes

2023-05-11 10:13 UTC, merged